// Generated by Nitron.
// Requested task: c++ for a snake game

#include <iostream>

int main() {
    std::cout << "Nitron Project" << std::endl;
    std::cout << "c++ for a snake game" << std::endl;
    return 0;
}
