import os

EXCHANGE_ID = "binance"
API_KEY = os.getenv("EXCHANGE_API_KEY", "")
API_SECRET = os.getenv("EXCHANGE_API_SECRET", "")

PAPER_TRADING = True

SYMBOLS = ["BTC/USDT", "ETH/USDT"]
TIMEFRAME = "15m"
CANDLE_LOOKBACK = 200

FAST_EMA = 12
SLOW_EMA = 26

RISK_PER_TRADE_PCT = 1.0
STOP_LOSS_PCT = 2.0
TAKE_PROFIT_PCT = 4.0
MAX_OPEN_POSITIONS = 3

CHECK_INTERVAL_SECONDS = 60

PAPER_STARTING_BALANCE_USDT = 1000
