#!/usr/bin/env python3
# Nitro Tools
# Termux tool generated by Nitron

import os
import platform

def main():
    print("Nitro Tools")
    print("Termux tool is running.")
    print("Python:", platform.python_version())
    print("System:", platform.system())

    home = os.path.expanduser("~")
    print("Home:", home)


if __name__ == "__main__":
    main()
