"""
Automation Script
Generated by Nitron
"""

import os
import shutil
from datetime import datetime


def backup_folder(source, destination):

    if not os.path.exists(source):
        print("Source folder not found.")
        return

    os.makedirs(destination, exist_ok=True)

    backup_name = datetime.now().strftime("%Y%m%d_%H%M%S")

    backup_path = os.path.join(
        destination,
        backup_name
    )

    shutil.copytree(source, backup_path)

    print("Backup completed:", backup_path)


if __name__ == "__main__":

    print("Nitron Automation Ready")
