"""
AI Chatbot
Generated by Nitron
"""

def chatbot():

    print("Nitron Chatbot Started")

    while True:

        user = input("You: ")

        if user.lower() in ["exit", "quit"]:

            print("Bot: Goodbye!")
            break

        print("Bot:", "You said:", user)


if __name__ == "__main__":
    chatbot()
