"""
VisionAI
Generated by Nitron AI
"""

class AI:

    def __init__(self):

        self.name = "VisionAI"

    def chat(self, message):

        return f"{self.name} received: {message}"


def main():

    ai = AI()

    print("=== " + ai.name + " ===")

    while True:

        text = input("You: ")

        if text.lower() in ["exit", "quit"]:

            break

        print(ai.chat(text))


if __name__ == "__main__":

    main()
