class AIModel:

    def __init__(self):

        self.memory = {}

    def chat(self, message):

        message = message.lower()

        if "hello" in message:
            return "Hello!"

        if "name" in message:
            return "I am an AI generated by Nitron."

        return "I'm still learning."
