# Nitron Project
# Generated by Nitron

def calculator():
    print("Nitron Project")
    print("1. Add")
    print("2. Subtract")
    print("3. Multiply")
    print("4. Divide")

    first = float(input("First number: "))
    operator = input("Operation (+, -, *, /): ")
    second = float(input("Second number: "))

    if operator == "+":
        result = first + second
    elif operator == "-":
        result = first - second
    elif operator == "*":
        result = first * second
    elif operator == "/":
        if second == 0:
            print("Cannot divide by zero.")
            return
        result = first / second
    else:
        print("Unknown operation.")
        return

    print("Result:", result)


if __name__ == "__main__":
    calculator()
