# ==================================================
# TestWebsite BACKEND
# Generated by Nitron
# ==================================================

from http.server import BaseHTTPRequestHandler, HTTPServer
import json


class Handler(BaseHTTPRequestHandler):

    def send_json(self, status, data):

        body = json.dumps(data).encode("utf-8")

        self.send_response(status)
        self.send_header("Content-Type", "application/json")
        self.send_header("Content-Length", str(len(body)))
        self.end_headers()

        self.wfile.write(body)


    def do_GET(self):

        if self.path == "/api/health":

            self.send_json(
                200,
                {
                    "status": "ok",
                    "project": "TestWebsite"
                }
            )

            return

        self.send_json(
            404,
            {"error": "Not found"}
        )


def main():

    server = HTTPServer(
        ("127.0.0.1", 8000),
        Handler
    )

    print("TestWebsite backend running on http://127.0.0.1:8000")

    try:
        server.serve_forever()
    except KeyboardInterrupt:
        print("Server stopped.")
    finally:
        server.server_close()


if __name__ == "__main__":
    main()
