"""
Coding Assistant
Generated by Nitron
"""

class AI:

    def __init__(self):
        self.name = "Coding Assistant"

    def run(self):

        print("Starting {}".format(self.name))
        print("AI that helps write and explain code.")


if __name__ == "__main__":

    AI().run()
